from math import pi
#Genome
NUM_INPUTS = 4
NUM_OUTPUTS = 1

MAX_CELLS = 2000
NUM_GENERATIONS = 50
SIMULATION_STEPS = 300

WORLD_WIDTH = 1000
WORLD_HEIGHT = 750
SOIL_HEIGHT = 250
LIGHT_ANGLE = pi / 4.0

CELL_MAX_GROWTH = 3

SEED_SEGMENTS = 12
SEED_RADIUS = 12

PLANT_EFFICIENCY = 100.
WATER_EFFICIENCY = .5
LIGHT_EFFICIENCY = 1.0

# 1.5 times the link start state
MAX_EDGE_LENGTH = 1.5 * (2*pi*SEED_RADIUS / SEED_SEGMENTS)
MAX_ANGLE = .95 * 2*pi


