from math import pi
#Genome
NUM_INPUTS = 6
NUM_OUTPUTS = 3

MAX_CELLS = 2000
NUM_GENERATIONS = 200
SIMULATION_STEPS = 250

WORLD_WIDTH = 1200
WORLD_HEIGHT = 800
SOIL_HEIGHT = 250
LIGHT_ANGLE = pi / 2.0

CELL_MAX_GROWTH = 3.0

SEED_SEGMENTS = 16
SEED_RADIUS = 16

PLANT_EFFICIENCY = 600.
WATER_EFFICIENCY = .1
LIGHT_EFFICIENCY = .6

FLOWER_COST = 1.0

__default_length = (2*pi*SEED_RADIUS / SEED_SEGMENTS)
MAX_EDGE_LENGTH = 1.5 * __default_length
MIN_EDGE_LENGTH = .5 * __default_length
MAX_ANGLE = .97 * 2*pi

WORLD_NUM_BUCKETS = 30
WORLD_GROUP_WIDTH = MAX_EDGE_LENGTH * 1.5
WORLD_BUCKET_SIZE = 500

CELL_SIZE = MAX_EDGE_LENGTH * 1.5
